[package]
name = "pt-launcher"
version = "0.1.2"
edition = "2021"

[dependencies]
sixtyfps = "0.1.5"
open = "1"
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }