[package]
name = "pt-launcher"
version = "0.1.2"
edition = "2021"

[dependencies]
slint = "0.2.0"
open = "2.0.2"
futures = "0.3.19"
image = "0.23.14"
reqwest = { version = "0.11.9", features = ["json"] }
tokio = { version = "1.16.1", features = ["full"] }
serde = { version = "1.0.136", features = ["derive"] }

[build-dependencies]
slint-build = "0.2.0"
