import { Menu } from "./menu.slint";
import { Home } from "./home.slint";
import { News } from "./news.slint";
import { NewsData } from "./newsdata.slint";
import { Settings } from "./settings.slint";
import { Market } from "./market.slint";
import { Credits } from "./credits.slint";

MainWindow := Window {
    property <int> tab: 0;
    property <[NewsData]> news: [];
    property <image> featured;

    title: "Project Trains - Launcher";
    background: #12171d;
    min-width: 890phx;
    min-height: 600phx;
    max-width: 1920phx;
    max-height: 1080phx;
    preferred-width: 1000phx;
    preferred-height: 650phx;

    callback blog-redirect();
    callback close();

    HorizontalLayout {
        padding: 10phx;
        width: 100%;
        Menu {
            change-tab(new-tab) => {
                tab = new-tab;
            }
            quit-launcher() => {
                root.close();
            }
        }
        if tab == 0: Home {
            featured-image: root.featured;
            forum-button-clicked() => { 
                root.blog-redirect();
            }
        }
        if tab == 1: Home {
            forum-button-clicked() => { 
                root.blog-redirect();
            }
        }
        if tab == 2: News {
            news : root.news;
            
            forum-button-clicked() => { 
                root.blog-redirect();
            }
        }
        if tab == 3: Market {
            forum-button-clicked() => { 
                root.blog-redirect();
            }
        }
        if tab == 4: Settings {
            forum-button-clicked() => { 
                root.blog-redirect();
            }
        }
        if tab == 5: Credits {
            forum-button-clicked() => { 
                root.blog-redirect();
            }
        }
    }
}