import { TopBar } from "./topbar.slint";
import { NewsData } from "./newsdata.slint";

Item := Rectangle {
    property <string> title;
    property <image> image;
    height: 150phx;
    max-width: 1200phx;

    ta := TouchArea {
        Rectangle { 
            border-radius: 12phx;
            height: 135phx;
            width: parent.width;
            clip: true;

            Image {
                height: 100%;
                width: parent.width;
                source: image;
                image-fit: cover;
            }
            Rectangle {
                height: parent.height;
                width: parent.width;
                animate background { duration: 0.2s; }
                background: @linear-gradient(0deg, ta.has-hover ? #171b208d : #171b20dc 0%, transparent 95%);
            }
            VerticalLayout {
                padding: 10phx;
                alignment: end;
                Text {
                    text: title;
                    font-size: 20phx;
                    color: white;
                    font-weight: 800;
                    overflow: TextOverflow.elide;
                }
            }
        }
    }
}

News := Rectangle {
    property <[NewsData]> news;
    background: #12171d;
    clip: true;

    callback forum-button-clicked();

    VerticalLayout { 
        padding-left: 20phx;
        padding-right: 20phx;
        TopBar {
            forum-click() => { 
                root.forum-button-clicked()
            }
        }
        Rectangle { height: 15phx; }
        VerticalLayout { 
            Flickable {
                VerticalLayout {
                    for data[i] in root.news : Item {
                        title: data.title;
                        image: data.cover;
                    }
                }
            }
        }    
    }
}